version: '3.5'

services:
  db:
    image: mysql
    container_name: wodbox-mysql
    restart: always
    # ports:
    #   - 33061:3306
    environment:
      MYSQL_DATABASE: 'kodbox'   
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'adminpwd'      
      MYSQL_ROOT_PASSWORD: 'adminpwd'
    volumes:
      - ./mysql:/var/lib/mysql
      
  app:
    image: kodcloud/kodbox
    ports:
      - 8888:80                       #左边80是使用端口，可以修改
    links:
      - db
      - redis
    volumes:
      - "./site:/var/www/html"      #./site是站点目录位置，可以修改
      - "./nginx:/etc/nginx"      #./site是站点目录位置，可以修改
      - "./etc:/usr/local/etc"      #./site是站点目录位置，可以修改
    restart: always

  redis:
    image: redis:alpine
    environment:
      - "TZ=Asia/Shanghai"
    restart: always
